-- TCG.market — email subscription capture (pre-launch: collection only, no sending).
-- Stores opt-ins for the weekly report. Kept OUT of every public read path: RLS is
-- enabled with NO policies, so the anon/publishable key gets nothing; only the
-- server (service-role key, which bypasses RLS) ever reads or writes it. No reader
-- module or public API touches this table — the sole accessor is
-- src/lib/subscribe/subscribers.ts.
-- Idempotent: safe to re-run (create if not exists).

create table if not exists public.report_subscribers (
  id                uuid primary key default gen_random_uuid(),
  email             text not null unique,          -- stored lowercased + trimmed (app-enforced)
  source            text,                           -- "report-page" | "footer" | ...
  created_at        timestamptz not null default now(),
  unsubscribe_token text not null unique,           -- long random, generated by the app
  unsubscribed_at   timestamptz                     -- null = active; set on unsubscribe
);
-- `email` + `unsubscribe_token` are UNIQUE (each already indexed) — the two lookup
-- paths (upsert-by-email, unsubscribe-by-token) are covered without extra indexes.

-- RLS on, no policies → identical lockdown to every other table in this DB.
-- (Server components + the API routes use the service-role key, bypassing RLS.)
alter table public.report_subscribers enable row level security;
